define autofs::mapfile($path)
{
	include autofs::params

	if !defined(Concat[$path])
	{
		concat
		{
			$path:
			owner  => $autofs::params::owner,
			group  => $autofs::params::group,
			mode   => '0644',
			notify => Service[$autofs::params::service],
		}
		
		concat::fragment
		{
			"autofs::mapfile ${title}":
			target  => "${path}",
			content => "# This file is automatically generated by Puppet\n#\n# Any changes made to this file will be lost on the next automated Puppet run!\n\n",
			order   => '100',
		}
	}
}
